# Generated by Django 3.0.4 on 2020-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200329_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
